### ISSUE TITLE
invalid certificate signature on my.voya.com

### ISSUE THREAD

**Issue by kkostrzewa** [yunzhu-li/certificate-info#22]
Visiting https://my.voya.com shows a *certificate signed by unknown authority* in certificate-info, but chrome reports it as valid.

![image](https://user-images.githubusercontent.com/19849201/79634543-0417a980-8139-11ea-8af8-f6a64fd92513.png)

![image](https://user-images.githubusercontent.com/19849201/79634565-24dfff00-8139-11ea-9aec-b583513f8c69.png)

My guess is the hardcoded table in https://github.com/blupig/certificate-info/blob/master/server/main.go#L35 needs some ♥

**Comment by yunzhu-li** [comment]
The Go standard library reads trusted CA certs from [these locations](https://golang.org/src/crypto/x509/root_linux.go) and I verified the root CA used by this website is included in the image. The hard-coded table is used to determine if the cert has extended validation.

It looks like the server isn't providing the intermediate cert during TLS handshake and therefore some clients might not be able to verify the chain of trust. I'm not sure how Chrome managed to figure out the intermediate cert but this should be a configuration issue of the website.

SSL Labs test shows incomplete chain: https://www.ssllabs.com/ssltest/analyze.html?d=my.voya.com&hideResults=on

Firefox shows SEC_ERROR_UNKNOWN_ISSUER:

![firefox](https://user-images.githubusercontent.com/1742004/79669289-5e336180-816f-11ea-8499-cc7e4e81f8b5.png)

I'm going to close this one since I'm not sure if this is actionable, feel free to re-open.
