### ISSUE TITLE
supporting Firefox?

### ISSUE THREAD

**Issue by FranklinYu** [yunzhu-li/certificate-info#24]
Firefox has a [very helpful API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest#accessing_security_information) to access the certificate information without needing a server. That said, since this API isn’t supported on any Chromium browsers, I’m not sure whether it’s easier to simply build a new browser extension. What do you think?

**Comment by yunzhu-li** [comment]
To me it looks like it will be easier to build a new one for Firefox and it should use the browser API when possible since that will provide the correct info of the connection, but I don't have plans to do it. Another unrelated issue is that I think the value of an extension showing validation levels may be decreasing as more organizations starting to use automated certificate issuers (Let's Encrypt and other automated certs provided by cloud service providers) and afaik they only offer DV.

**Comment by FranklinYu** [comment]
That’s fair. Closing this issue; feel free to re-open if you change your mind.
